### PR TITLE
Added answers for 1819 Sem1&2, 1920 Sem1

### PR DESCRIPTION
**Pull request by junghon3709**
Please do help me vet through this. Thank you!

### CODE REVIEW

**Comment by mhq199657** [comment]
Thank you so much!

**Comment by mhq199657** [comment]
I checked 18/19 Sem 1 paper. All is good except Question 1.

For that function f=x(x-6)^{1/5}, due to the presence of the fractional power, the domain of the function is (6,+\infty), since (x-6)^{1/5}=Exp[1/5*Log[x-6]], and we do not have knowledge about the natural log over non-positive values.

I will proceed on checking 18/19 Sem 2 tomorrow.

Do you guys mind uploading 19/20 Sem 1 question paper to this PR too? The libportal does not have that uploaded yet.

**Comment by junghon3709** [comment]
Alright thank you, I'll fix those changes tomorrow or by Monday. I'll
upload the 19/20 papers tomorrow as well.

**Comment by mhq199657** [comment]
18/19Sem2 answers are all correct. Fantastic work!

**Comment by junghon3709** [comment]
Hi, for the 18/19 Sem 1 paper, Desmos tells me that the output of the function can be real for all x. I'm not sure if the reasoning of (x-6)^{1/5}=Exp[1/5*Log[x-6]] is correct though since this might not hold true for x-6<0?

**Comment by mhq199657** [comment]
Hey, the equation is due to the definition of generalized exponential function. 

Consider the example of (-1)^{1/5}. Let its value be a. Then we know a^5 = -1. Admittedly we can have a = -1, but is this the value we want, given that it has five roots, and one of it is real?

**Comment by junghon3709** [comment]
But I guess in the case of MA1102, we aren't required to know this right?
Furthermore, desmos gives a real output for all x values when I try
plotting the graph.

**Comment by mhq199657** [comment]
If we choose the real root as the result of fractional power, your answer is indeed correct. Sorry for being too cautious..

**Comment by junghon3709** [comment]
Thanks for raising that up though, really made me think about when a
function is defined for fractional powers :)

**Review by mhq199657 — APPROVED** [review]
This is excellent work! Thank you for your contributions!

**Comment by junghon3709** [comment]
Thank you! Actually I realised a typo for the 19/20 Paper in qn 8. There's a mutiplication symbol in the last 2 lines. Can I resubmit a pull request?

**Comment by mhq199657** [comment]
Sure! Be my guest!

**Pull request merged**
